### ISSUE TITLE
Cached Pages don't get compressed

### ISSUE THREAD

**Issue by Rembrant** [paolochiodi/htmlcompressor#11]
I am using actionpack-page_caching to cache static pages and the htmlcompressor as middleware. When I look at my Rails server's response source code in Chrome DevTools it is compressed but when I look at the source of my Page Cached file it is not compressed.

How would this best be fixed? Thanks.

**Comment by paolochiodi** [comment]
I'm going to close this old issue, at the moment I'm not looking to include into the gem a specific rails hook.

Thank you @le0pard for sharing your solution
