### ISSUE TITLE
Doesn't work together with Rack::Deflater

### ISSUE THREAD

**Issue by dyatlov** [paolochiodi/htmlcompressor#19]
When I use in config both HtmlCompressor and Rack::Deflater - I get data stream error:

```
config.middleware.use HtmlCompressor::Rack
config.middleware.use Rack::Deflater
```

**Comment by BrokenChair** [comment]
It seems to work if I reverse the order

config.middleware.use Rack::Deflater
config.middleware.use HtmlCompressor::Rack

Is that correct though? Can the compression work after the content has been deflated?

**Comment by dyatlov** [comment]
of course CAN'T :)

**Comment by BrokenChair** [comment]
My browser shows that it is gzipped and the content is definitely compressed. Google Pagespeed confirms that the content is minified and gzipped.

Running rake middleware definitely shows that Deflater is above HtmlCompressor. What sorcery is this?

**Comment by dyatlov** [comment]
heh.. okay

**Comment by paolochiodi** [comment]
Old issue
