### ISSUE TITLE
How do I disable compression for specific pages / view, etc?

### ISSUE THREAD

**Issue by nadavb** [paolochiodi/htmlcompressor#20]

**Comment by marvindanig** [comment]
Guess, I'm gonna need this too. Was there any movement on this?

**Comment by nadavb** [comment]
Any progress here?

**Comment by nadavb** [comment]
Okay, I did it myself - see the pull request. Works great! @marvindanig  -> you can take it from there

**Comment by marvindanig** [comment]
:+1: will give it a look in a bit.

**Comment by marvindanig** [comment]
Looks good, thanks @nadavb! 

I hope @paolochiodi will merge this pull request (and other two) into the master soon.

**Comment by paolochiodi** [comment]
Old issue
