### ISSUE TITLE
Warnings with Ruby 2.2.0

### ISSUE THREAD

**Issue by dmasur** [paolochiodi/htmlcompressor#23]
Hi paolochiodi,

thanks for your gem. 

There are new warnings with ruby 2.2.0:

/Users/dmasur/.rvm/gems/ruby-2.2.0/gems/htmlcompressor-0.1.2/lib/htmlcompressor/compressor.rb:112: warning: duplicated key at line 132 ignored: :javascript_compressor
/Users/dmasur/.rvm/gems/ruby-2.2.0/gems/htmlcompressor-0.1.2/lib/htmlcompressor/compressor.rb:113: warning: duplicated key at line 133 ignored: :css_compressor

the warnings is pretty clear. you declared this twice. I don't know why, maybe for documentation, so i didn't open a pull request.

Can you take a look at it?

**Comment by Florian95** [comment]
:+1:

**Comment by izelnakri** [comment]
This is actually fixed on the master branch already:  https://github.com/paolochiodi/htmlcompressor/commit/4d793ad7a0a6ccc60b723aa86aa25be2ae099998. However the ruby gem has not been updated yet. My suggestion would be to open your gem via ```bundle open htmlcompressor``` and delete those two lines.

**Comment by paolochiodi** [comment]
@izelnakri @Florian95 @dmasur I'm working on a new version collecting all the pull requests and feedback received. Unfortunately I have only spare time to work on this, thus may require another couple of days before publishing

**Comment by MrRio** [comment]
@paolochiodi Could you push a point release which is just this bug cherry picked?

**Comment by izelnakri** [comment]
yes, @paolochiodi please push master to rubygems.

**Comment by paolochiodi** [comment]
Hi guys,
sorry for taking so long, but the fix is now published on rubygems under version 0.2.0
