### ISSUE TITLE
NameError: uninitialized constant HtmlCompressor

### ISSUE THREAD

**Issue by ginolon** [paolochiodi/htmlcompressor#31]
Following this guide (https://remino.net/rails-html-css-js-gzip-compression/) I got an error:

NameError: uninitialized constant HtmlCompressor
remote:        /tmp/build_bae5e5126f5adcb967c7086926599cf4/config/initializers/compression.rb:24:in `block in <top (required)>'

on Heroku.

Rails 4.2.1.

Why?

I have to install your Middleware? A gem?

**Comment by ginolon** [comment]
You can close this. I fixed.

**Comment by monteirobrena** [comment]
Hi @ginolon, how you fixed this error?
Thanks.

**Comment by adekbadek** [comment]
I have the same problem. @ginolon, could you please share the solution?
