### ISSUE TITLE
Gem is slowing down the server by 3 seconds or so.

### ISSUE THREAD

**Issue by nadavb** [paolochiodi/htmlcompressor#36]
Folks, 
I've used this Gem for around 6 months, and just discovered that it added ~3 seconds to the response time of my server. This is really bad. Please see this as a warning - if you think to try it - make sure you measure your overall response time of the server (whether if it's apache or else). I removed it completely  and now the website is really fast.

The right solution should be else. Either doing the compression in a low level language, to add speed, or, better, doing the compression not in real-time. Something like assets pipeline for the views and partials.

**Comment by paolochiodi** [comment]
Thank you for reporting this, and sorry for the bad experience.
I'll add a disclaimer on the README to discourage usage of this gem on real-time
